### ISSUE TITLE
Invalid parameter key_source on Apt::Source[zabbix] at /etc/puppet/environments/myenv/modules/zabbix/manifests/repo.pp:144 on node XXXXX

### ISSUE THREAD

**Issue by drthornt** [dj-wasabi/puppet-zabbix#101]
I'm having an interesting error.

According to the docs I don't need to add anything more than:

  class { 'zabbix::agent':
    server => 'ipaddress',
  }

which I did.

Here is the code snippet:

      'ubuntu' : {
        apt::source { 'zabbix':
          location   => "http://repo.zabbix.com/zabbix/${zabbix_version}/ubuntu/",
          release    => $ubuntu,
          repos      => 'main',
          key        => 'FBABD5FB20255ECAB22EE194D13D58E479EA5ED4',
          key_source => 'http://repo.zabbix.com/zabbix-official-repo.key',
        }

* my version is 1.5.0
* I'm using ubuntu
* I'm using puppetlabs/apt 2.0.1 which I think is the root of the problem. 

Are you using an "old" apt::source definition?

David Thornton

**Comment by irenegarvin** [comment]
Had the same issues and needed to downgrade apt to 1.8 to get it working again.

**Comment by irenegarvin** [comment]
apt patched.. going to test with the update 2.1.0

**Comment by dj-wasabi** [comment]
Does the 2.1.0 version work?

**Comment by irenegarvin** [comment]
sorry for missing this response, after the patch, everything worked fine.

**Comment by luiszandonadi** [comment]
i've the same problem, but im using debian wheezy

**Comment by dj-wasabi** [comment]
Hi @luiszandonadi 

What version of the yum module are you using?

**Comment by Oyabi** [comment]
+1 I have exactly the same error on a Debian 8.2 server.
├── puppetlabs-apt (v2.2.0) 
└── wdijkerman-zabbix (v1.6.0)
It's really weird because sometime all is fine and zabbix is installed without error message, and sometine not.
Regards.

**Comment by davideagle** [comment]
I too have this problem, apt v 2.2.0, tried to downgrade to 2.1.0 and no luck, the apt module change how it deals with keys some time back if I remember correctly

**Comment by ericsysmin** [comment]
Looking at their site, 

> if $key_source != undef {
    warning("\$key_source is deprecated and will be removed in the next major release, please use \$key => { 'source' => ${key_source} } instead.")
  }

It appears we need to change to $key this was detailed in 2.2.x at https://github.com/puppetlabs/puppetlabs-apt/blob/2.2.x/manifests/source.pp#L59

**Comment by ericsysmin** [comment]
@dj-wasabi I believe you can close this, looks like edits required were already performed.

**Comment by dj-wasabi** [comment]
Will close the issue. It can always be reopened again.
