### ISSUE TITLE
zabbix_version ignored

### ISSUE THREAD

**Issue by elexpander** [dj-wasabi/puppet-zabbix#105]
On params.pp:
````
$zabbix_version = '2.4'
````
On my manifest
````
class { '::zabbix::agent':
  zabbix_version => '2.2',
}
````
This results in zabbix-agent 2.4 installed 

This can be easily fixed passing zabbix_version to class repo in agent.pp:
````
if $manage_repo {
  #include zabbix::repo
  class { 'zabbix::repo':
    zabbix_version => $zabbix_version,
  }
  Package['zabbix-agent'] {require => Class['zabbix::repo']}
}
````
Exactly same issue on proxy.pp and very likely server.pp.

**Comment by dj-wasabi** [comment]
Hi,

Thanks you for making time to create this issue. Due to some personal issues I didn't had any time to investigate it. I have an fix for this in the next few days. I'll let you know when you can download it.

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
It is in release 1.6.0 which was released few minutes ago. Can be downloaded from the Forge and github.
