### ISSUE TITLE
Feature Request: add charset/collate option during a mysql db resource creation

### ISSUE THREAD

**Issue by iclements** [dj-wasabi/puppet-zabbix#107]
Hi, I would like to know if its possible to add the charset and collate options during the create mysql db resource creation as it defaults to the default variables within the mysql module

example switch to bin form general_ci
charset       = 'utf8'
collate        = 'utf8_bin'

**Comment by dj-wasabi** [comment]
Hi Ian,

At the moment I'm busy with some testing. If these succeed, I'll push them to github in the next few days (I'll update this ticket).
Hopefully I can create an release in the next week to, so it will also be available on the forge.

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
It is in release 1.6.0 which was released few minutes ago. Can be downloaded from the Forge and github.
