### ISSUE TITLE
Split Zabbix Server Class into Components

### ISSUE THREAD

**Issue by ben-albon** [dj-wasabi/puppet-zabbix#11]
The Zabbix Server class, as is currently defined in the wdijkerman-zabbix module, could actually be split into the 3 components:
* Zabbix Server
* Zabbix WebUI
* Zabbix DB

In order to scale zabbix effectively, it's best practice to run each of these components on separate nodes.

(for example, http://blog.zabbix.com/scalable-zabbix-lessons-on-hitting-9400-nvps/2615/)

As it stands, it does not seem possible to use the wdijkerman-zabbix module to install the zabbix server on one node, the WebUI on a second, and the Database on a third.

**Comment by dj-wasabi** [comment]
I just released v1.0.0.
I hope you enjoy it. :-)

**Comment by karolisc** [comment]
Hi Werner,

Nice work, but I would like it to be more structured.


It could have such classes:
```
    zabbix::server::server
    zabbix::server::web
    zabbix::server::database (pseudo)
```
same for proxy:
```
    zabbix::proxy::proxy
    zabbix::proxy:database  (pseudo)
```

Pseudo classes for all in one scenarios
```
   zabbix::server (){
     class { zabbix::server::server:
     }
     class { zabbix::server::web:
     }
     class { zabbix::server::database:
     }
   }
```
and   
```
   zabbix::proxy (){
     class { zabbix::proxy::proxy:
     }
     class { zabbix::proxy:database:
     }
   }
```
Advanced setups would call real classes directly.
I think this way node manifest would be much more readable.

Karolis

**Comment by dj-wasabi** [comment]
HI Karolis,

Let me think about it. For now this setup is something I can live with.
So if I take this road, don't expect it the next month/release, as this take some time. :-)

I've created in my own personal jira an ticket for this.
As the original request is solved, I'll close this ticket.

Kind regards,
Werner
