### ISSUE TITLE
Agent Config Template

### ISSUE THREAD

**Issue by ParFlesh** [dj-wasabi/puppet-zabbix#112]
In the template for zabbix_agentd.conf.erb line 40 the config parameter SourceIP is defined in lower case.  This will cause agent to fail on startup with unknown parameter error.  Changing from sourceip to SourceIP should fix the issue.

**Comment by dj-wasabi** [comment]
Hi ParFlesh,

Thank you for noticing, I fixed it and should be available within the next few days.

**Comment by dj-wasabi** [comment]
It is in release 1.6.0 which was released few minutes ago. Can be downloaded from the Forge and github.

**Comment by ParFlesh** [comment]
Thanks, you are awesome.
