### ISSUE TITLE
zabbix::template failing - undefined method `configurations'

### ISSUE THREAD

**Issue by claflico** [dj-wasabi/puppet-zabbix#113]
CentOS 7, Puppet 3.8.1, module version 1.5.0.

Using role/profile method. Here is what my zabbix.pp looks like:
class profile::zabbix {

  class { '::apache':
    mpm_module => 'prefork',
  }
  include ::apache::mod::php
  # Install zabbix
  class { '::zabbix': }

  zabbix::template { 'Template Database MongoDB':
    templ_source => 'puppet:///modules/profile/zabbix/MongoDB_Plugin_template_export.xml'
  }

}

Every time I try to do a puppet run now on the zabbix server I get: Error: /Stage[main]/Profile::Zabbix/Zabbix::Template[Template Database MongoDB]/Zabbix::Resources::Template[Template Database MongoDB]/Zabbix_template[Template Database MongoDB]: Could not evaluate: undefined method `configurations' for #<ZabbixApi:0x00000003a506d8>

Ideas?

**Comment by dj-wasabi** [comment]
Hi,

Thank you for making time to create this issue.
Can you verify if the gem 'zabbiapi' is installed? You have configured the `manage_resource => true` on zabbix class?

**Comment by claflico** [comment]
Looks like it is:
sudo gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (1.10.6)
io-console (0.4.2)
json (1.7.7)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
zabbixapi (2.4.0)

And here's my hiera settings, sorry I forgot them initially:
zabbix::agent::manage_resources: true
zabbix::agent::server: 'X.X.X.X'
zabbix::agent::serveractive: 'X.X.X.X'
zabbix::agent::zbx_group: "%{::project}-%{::tier}"
zabbix::database_type: 'mysql'
zabbix::manage_resources: true
zabbix::zabbix_timezone: 'America/Chicago'
zabbix::zabbix_url: 'zabbix.XXXX.XXX'

Thanks

**Comment by claflico** [comment]
Not happening anymore.
