### ISSUE TITLE
Userparameter with Foreman 

### ISSUE THREAD

**Issue by georgesouzafarias** [dj-wasabi/puppet-zabbix#117]
I'm using your puppet module in my environment. I haven't  a lot of experience with puppet, but I'm using the foreman's web interface to manager my configurations.

My questions is: 

How to configure userparameter using the web interface? 

For example: 

userparameter=pje.available,/usr/local/sbin/test_pje

Thank you

**Comment by inspired-geek** [comment]
Hello!
@georgesouzafarias,did you find the answer?

**Comment by georgesouzafarias** [comment]
Not, I'm waiting for.

**Comment by inspired-geek** [comment]
Actually I found a solution.
As Dominic said here https://groups.google.com/d/msg/foreman-users/o-Sqjo-n21A/66pEAIG17PYJ

> You can't instantiate resources (defined types, or native) over the 
> Puppet ENC interface.  Maybe use create_resources instead, e.g. 

>```ruby
>define foo($a, $b) { 
>  notify { "$title: got $a and $b": } 
>} 

> class createfoo($data){ 
 > create_resources(foo, $data) 
>} 
>```
>Then in foreman for the createfoo class, set the data parameter to: 
>```yaml
>--- 
>data: 
>  first: 
>    a: "param 1a" 
>    b: "param 1b" 
>  second: 
>    a: "param 2a" 
>    b: "param 2b" 
>```

So I've created module on puppet master `puppet module generate nrzabbix` and in `manifests/init.pp` I've put 
```ruby
class nrzabbix($data){
        create_resources(zabbix::userparameters, $data)
}
```

Then in foreman UI I've imported newly created module. It has only one smart parameter data which could be overridden in foreman
![image](https://cloud.githubusercontent.com/assets/1792014/10131286/d0477bd4-65d7-11e5-88cb-e7f81e421ef3.png)

For example my UserParameter for montoring mongodb is described as
```yaml
mongo:
  source: puppet:///modules/nrzabbix/mongo.conf
```

And content of nrzabbix/files/mongo.conf is
```
UserParameter=mongo.coll.count[*],echo "db.setSlaveOk();db.getCollection('$1').count()" | /opt/mongo/bin/mongo processor | sed -n 3p
UserParameter=mongo.db.queries,echo "db.currentOp().inprog.length" | /opt/mongo/bin/mongo processor | sed -n 3p
```

Then I've added this class to certain config group for my mongodb servers.
In YAML for a host I've got
```yaml
---
classes:
  nrzabbix:
    data:
      mongo:
        source: puppet:///modules/nrzabbix/mongo.conf
```
On a host:
```
[root@nr-db-cl-c3 ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for nr-db-cl-c3.nr.voskhod.ru
Info: Applying configuration version '1443431001'
Notice: /Stage[main]/Nrzabbix/Zabbix::Userparameters[mongo]/File[/etc/zabbix/zabbix_agentd.d/mongo.conf]/ensure: defined content as '{md5}9e444bd9fecf403b518547648373c9ba'
Info: /Stage[main]/Nrzabbix/Zabbix::Userparameters[mongo]/File[/etc/zabbix/zabbix_agentd.d/mongo.conf]: Scheduling refresh of Service[zabbix-agent]
Notice: /Stage[main]/Zabbix::Agent/Service[zabbix-agent]: Triggered 'refresh' from 1 events
Notice: Finished catalog run in 3.28 seconds
```
and
```
[root@nr-db-cl-c3 ~]# cat /etc/zabbix/zabbix_agentd.d/mongo.conf
UserParameter=mongo.coll.count[*],echo "db.setSlaveOk();db.getCollection('$1').count()" | /opt/mongo/bin/mongo processor | sed -n 3p
UserParameter=mongo.db.queries,echo "db.currentOp().inprog.length" | /opt/mongo/bin/mongo processor | sed -n 3p
```

Hope this could help

**Comment by dj-wasabi** [comment]
Hi @inspired-geek 

Thank you for this reply.

You could use this class: 'zabbix::userparameter.pp' instead of creating your own.
(Without the s.. ;-)) 

Can I update the readme for using userparameters with this information you provided?

Thanks!

**Comment by inspired-geek** [comment]
@dj-wasabi, of course you could!
It's non-obvious so I felt the need to dive deep into details :)

**Comment by chernogorsky** [comment]
Hi, class zabbix::userparameter.pp has no smart class parameter
This Puppet class has no parameters in its signature. 
To update the class signature, go to the Puppet Classes page and select "Import".

Foreman 1.9.2

**Comment by chernogorsky** [comment]
class zabbix::userparameter_fix($data) {
  notify { "Userparameter data $data": }
  validate_hash($data)
  create_resources('zabbix::userparameters', $data)
}

This work as expected
