### ISSUE TITLE
Missing LDAP packages

### ISSUE THREAD

**Issue by torgrimt** [dj-wasabi/puppet-zabbix#140]
Hi.

In order to get the ldap functionality working, the php-ldap package is needed. I could not find any references to this in the code or in the readme.
Solved by the following extra code:
  $package = $::osfamily ? {
    'RedHat' => 'php-ldap',
    'Debian' => 'php5-ldap',
    default  => 'php-ldap',
  }
  package { $package :
    ensure => present,
  }

**Comment by dj-wasabi** [comment]
Hi @torgrimt 

Yes thats right, these php packages aren't part in this module. Not everyone needs to have these packages installed and it is not the responsibility of this module to take care of these. Just like this module doesn't install Apache and Php, this is handled by the Apache Puppet Module.

You'll have to configure this in your site manifest.

Kind regards,
Werner
