### ISSUE TITLE
Repo url in RHEL or Oracle Linux

### ISSUE THREAD

**Issue by inspired-geek** [dj-wasabi/puppet-zabbix#142]
Thanks for the module I use it a lot!
But I've discovered a problem with my Oracle Linux.
Module creates repo with baseurl like this

    baseurl=http://repo.zabbix.com/zabbix/2.4/rhel/$releasever/$basearch/

Which resolves in `http://repo.zabbix.com/zabbix/2.4/rhel/6Server/x86_64` which is bad.
Are there any workarounds or fixes?

**Comment by dj-wasabi** [comment]
Hi,

I just committed and pushed an fix. Would you please test it?

Kind regards,
Werner

**Comment by inspired-geek** [comment]
Hello!
Now it works as expected!
Thanks a lot!
