### ISSUE TITLE
Server and Proxy templates are inconsistent

### ISSUE THREAD

**Issue by Moncky** [dj-wasabi/puppet-zabbix#144]
The Server and Proxy templates are inconsistent where applying memory limits to caches

For example the CacheSize option on the Server is:

CacheSize=<%= @cachesize %>

whilst on the Proxy is:

CacheSize=<%= @cachesize -%>M

Ideally this should be one or the other so that the puppet code is also then written consistently

**Comment by dj-wasabi** [comment]
Hi @Moncky 
You are right. Will fix it.

Thank you for mentioning!

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
I pushed an fix. 
Try to release this weekend the 1.8.0 release which holds this fix.

**Comment by dj-wasabi** [comment]
Released yesterday on the Forge.
