### ISSUE TITLE
No LDAP Support

### ISSUE THREAD

**Issue by elricsfate** [dj-wasabi/puppet-zabbix#149]
No Support For Setting Authentication out of the box. 

For example, you may want to set authentication to LDAPS and install the relevant certs so LDAP authentication is working

**Comment by elricsfate** [comment]
See  #150 

I added partial support for this. It should be possible to place the certificates in place though GUI configuration is still required for LDAP auth itself.

**Comment by elricsfate** [comment]
Oh yes, and in case he isn't alerted pinging @dj-wasabi

**Comment by dj-wasabi** [comment]
hi @elricsfate 
I did see it, but I didn't had the change to take a look at it. :-)

Looks very good!
