### ISSUE TITLE
SQlite isn't a supported DB for Proxy?

### ISSUE THREAD

**Issue by Wicaeed** [dj-wasabi/puppet-zabbix#151]
Greetings, having a fun time setting up Zabbix Agents with your module! I'm currently in the process of trying to set up a Zabbix Proxy for a remote site and running into an issue trying to use SQlite. Namely, setting the `database_type` to `sqlite` doesn't do anything when you run the puppet agent, and the Zabbix Proxy fails to start, complaining that it can't locate the sqlite DB files.

Reading through the Zabbix Proxy documentation, when specifying SQlite as the DB, you need to declare where the SQlite db file actually resides on the filesystem in order to use it. Currently with the existing params file it doesn't look like this is possible.

Is such capacity planned, or am I better off trying to use Postgres or MySQL as the DB backend for the proxy?

**Comment by dj-wasabi** [comment]
Hi @Wicaeed 
It should be supported. I'll try to investigate and see what is needed.
Will let you know.

**Comment by dj-wasabi** [comment]
Hi @Wicaeed 

I have configured my test setup like this:
```
class { 'zabbix::proxy':
  zabbix_server_host => 'zabbix.example.com',
  database_type      => 'sqlite',
  database_name      => '/tmp/database',
}
```
This works. 
```
[root@puppetdev ~]# ls -l /tmp/database
-rw-r--r-- 1 zabbix zabbix 460800 Jan 28 19:20 /tmp/database
```
When starting the Proxy, it notices that the database does not exists and will create one.
When specifying the database_name, Zabbix needs to have write access to the directory where you please your database.

Kind regards,
Werner

**Comment by Wicaeed** [comment]
Interesting. It looks as if when specifying a location outside of the `/tmp` directory (like `/etc/zabbix`) (or even a folder within the `/tmp` directory, like `/tmp/zabbix`) the SQlite db file never gets created, despite having permissions to create files/folders.

I changed the db location to `/tmp/zabbix-proxy` and that works fine. It might be worth noting that limitation in the documentation :)

**Comment by dj-wasabi** [comment]
Hi @Wicaeed 
In my environments, /etc/zabbix is owner by user root. So it won't create the database.
Did you create the /tmp/zabbix directory yourself, or is also owned by user root?

**Comment by Wicaeed** [comment]
Ah I see, the permissions themselves are correct for the zabbix files in `/etc/zabbix` but the parent directory still has root as the default owner/user, same for `/tmp`

Mystery solved!
