### ISSUE TITLE
Database is always managed

### ISSUE THREAD

**Issue by subkowlex** [dj-wasabi/puppet-zabbix#153]
Hi,
I use multiple hosts setup where zabbix proxy db is on an external server.
That's why I use zabbix::proxy::manage_database: false

But on every run puppet tries to update:

`Error: cd /usr/share/zabbix-*-mysql && if [ -f schema.sql.gz ]; then gunzip schema.sql.gz ; fi && mysql -h 'db-host' -u 'db_user' -p'password -D 'db' < schema.sql && touch /etc/zabbix/.schema.done returned 1 instead of one of [0]
Error: /Stage[main]/Zabbix::Database::Mysql/Exec[zabbix_proxy_create.sql]/returns: change from notrun to 0 failed: cd /usr/share/zabbix-*-mysql && if [ -f schema.sql.gz ]; then gunzip schema.sql.gz ; fi && mysql -h 'db_host' -u 'db_user' -p'db_pass' -D 'db' < schema.sql && touch /etc/zabbix/.schema.done returned 1 instead of one of [0]`

Any idea what's wrong?

**Comment by dj-wasabi** [comment]
Hi @subkowlex 

Thank you for making time to create this issue.
When reviewing the code, it seems that when manage_database is set to false in the proxy.pp, it won't create the database but it will execute the SQL scripts. That is not how it should be, so I will fix this.

I'll let you know when this is fixed.
Kind regards,
Werner

**Comment by dj-wasabi** [comment]
Hi,

This is fixed in 2.0.0 which is available since yesterday.
