### ISSUE TITLE
The puppetgem fact is incorrect for Puppet 4 AIO installation

### ISSUE THREAD

**Issue by rnelson0** [dj-wasabi/puppet-zabbix#157]
According to the puppetgem fact, the [presence of /etc/puppetlabs/puppet/puppet.conf](https://github.com/dj-wasabi/puppet-zabbix/blob/master/lib/facter/puppetgem.rb#L5-L6) indicates that `pe_gem` is the proper gem provider. In the Puppet 4 AIO installation, this file is present in the FOSS edition of puppet-agent.
````
[root@zabbix ~]# rpm -ql puppet-agent | grep /etc/puppetlabs/puppet/puppet.conf
/etc/puppetlabs/puppet/puppet.conf
[root@zabbix ~]# rpm -qi puppet-agent
Name        : puppet-agent
Version     : 1.3.2
Release     : 1.el7
Architecture: x86_64
Install Date: Thu 14 Jan 2016 01:04:44 PM UTC
Group       : System Environment/Base
Size        : 102953686
License     : See components
Signature   : RSA/SHA1, Wed 02 Dec 2015 11:21:40 PM UTC, Key ID 1054b7a24bd6ec30
Source RPM  : puppet-agent-1.3.2-1.el7.src.rpm
Build Date  : Wed 02 Dec 2015 07:31:43 PM UTC
Build Host  : pz30efh339jcnfe.delivery.puppetlabs.net
Relocations : (not relocatable)
Vendor      : Puppet Labs
URL         : https://www.puppetlabs.com
Summary     : The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, hiera and mcollective.
Description :
The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, hiera and mcollective.
````
The `puppetgem` fact needs to adjust for this and better detect the proper gem provider. I've looked at how other modules address this and it appears that few use facts and instead use some complicated if statements, such as in [hunner/hiera](https://github.com/hunner/puppet-hiera/blob/d594244af41e92811cf0f04eacddc74e22856c74/manifests/params.pp#L18-L51), since there doesn't seem to be a reliable fact for this or a stdlib function.

**Comment by dj-wasabi** [comment]
I'll close this issue, as this is fixed by @rnelson0 himself.
