### ISSUE TITLE
zabbixapi gem fails to install (ubuntu 14.04)

### ISSUE THREAD

**Issue by karolisc** [dj-wasabi/puppet-zabbix#16]
Hi Werner,

After enabling manage_resources zabbixapi gem fails to install.

**Error 1:**
`require': no such file to load -- mkmf (LoadError)
    from extconf.rb:36

**Error 2:**
Error: Could not update: Execution of '/usr/bin/gem install -v 2.4.0 --no-rdoc --no-ri zabbixapi' returned 1: Building native extensions.  This could take a while...
ERROR:  Error installing zabbixapi:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
creating Makefile

make
sh: 1: make: not found

The module misses these packages:
sudo apt-get install ruby1.9.1-dev
sudo apt-get install build-essential

**Comment by dj-wasabi** [comment]
I just released v1.0.0 now. It is fixed.
