### ISSUE TITLE
database is being managed even if manage_database is false

### ISSUE THREAD

**Issue by ericsysmin** [dj-wasabi/puppet-zabbix#170]
Notice: /Stage[main]/Zabbix::Database::Mysql/Exec[zabbix_server_create.sql]/returns: /bin/sh: line 0: cd: /usr/share/doc/zabbix-*-mysql-2.4*/create: No such file or directory
Error: cd /usr/share/doc/zabbix-*-mysql-2.4*/create && if [ -f schema.sql.gz ]; then gunzip schema.sql.gz ; fi && mysql -h 'localhost' -u 'zabbix_server' -p'zabbix' -D 'zabbix' < schema.sql && touch /etc/zabbix/.schema.done returned 1 instead of one of [0]
Error: /Stage[main]/Zabbix::Database::Mysql/Exec[zabbix_server_create.sql]/returns: change from notrun to 0 failed: cd /usr/share/doc/zabbix-*-mysql-2.4*/create && if [ -f schema.sql.gz ]; then gunzip schema.sql.gz ; fi && mysql -h 'localhost' -u 'zabbix_server' -p'zabbix' -D 'zabbix' < schema.sql && touch /etc/zabbix/.schema.done returned 1 instead of one of [0]
Notice: /Stage[main]/Zabbix::Database::Mysql/Exec[zabbix_server_images.sql]: Dependency Exec[zabbix_server_create.sql] has failures: true
Warning: /Stage[main]/Zabbix::Database::Mysql/Exec[zabbix_server_images.sql]: Skipping because of failed dependencies
Notice: /Stage[main]/Zabbix::Database::Mysql/Exec[zabbix_server_data.sql]: Dependency Exec[zabbix_server_create.sql] has failures: true
Warning: /Stage[main]/Zabbix::Database::Mysql/Exec[zabbix_server_data.sql]: Skipping because of failed dependencies
Notice: /Stage[main]/Zabbix::Server/Service[zabbix-server]: Dependency Exec[zabbix_server_create.sql] has failures: true
Warning: /Stage[main]/Zabbix::Server/Service[zabbix-server]: Skipping because of failed dependencies
Notice: Finished catalog run in 0.65 seconds

even though 
zabbix::params::manage_database: false
zabbix::database::manage_database: false

**Comment by ericsysmin** [comment]
i have fixed this in the patch-6 with zabbix::server::manage_database: false now works and stops the errors from occuring

**Comment by jk2l** [comment]
The issue is not truly resolved. The parameter didn't get pass down from base class to zabbix::server

**Comment by bastelfreak** [comment]
Hi @jk2l, thanks for reporting this. Are you able to provide a patch for it?

**Comment by jk2l** [comment]
already did. please check the pull request #249
