### ISSUE TITLE
write more rspec tests to test zabbix 3.0

### ISSUE THREAD

**Issue by ericsysmin** [dj-wasabi/puppet-zabbix#176]

**Comment by dj-wasabi** [comment]
I've added some tests for some Zabbix 3.0 specifics.

**Comment by dj-wasabi** [comment]
I just pushed an release (v2.2.0) to the forge.

**Comment by dj-wasabi** [comment]
With the next 2.3.0 release a lot of improvements are added. I close this ticket.
