### ISSUE TITLE
Custom API query?

### ISSUE THREAD

**Issue by ITler** [dj-wasabi/puppet-zabbix#179]
Hello,

I'm new to zabbix and I want to use your module to setup monitoring in my environment. I'd like to get full automation of zabbix configuration. I've seen, that there is no possibility to manage zabbix *actions* via API as the underlying library does not support that. Obviously there are good reasons, why, so at least I am looking for an opportunity to send custom queries (custom JSON) to the API using your module (to handle authentication). If I scanned your module's code correctly, currently I have no possibility to send custom queries, right? If so, this is a feature request else I need an oculist. :smile: 

Thank you
ITler

**Comment by dj-wasabi** [comment]
Hi @ITler 

No, there is no way to send customer queries. When you have an PuppetDB you can automate some things (Like adding hosts and proxies, assign and upload templates), but thats it.

**Comment by ITler** [comment]
It's a pity. I assume, there are no plans to extend that module. Due to my limited ruby skills and time resources, I currently can't do it myself.
