### ISSUE TITLE
Zabbix as default vhost

### ISSUE THREAD

**Issue by szemlyanoy** [dj-wasabi/puppet-zabbix#180]
Hi folks,

Did anyone face with issue when access to zabbix UI by IP address points to default vhost which is effectively just /var/www/  ?

I propose to make change in 
 apache::vhost { $zabbix_url }
and
apache::vhost { "${zabbix_url}_nonssl"}
resources to add attribute
manage_docroot => false

Tested on my env, I can now access Zabbix by IP.

BR,
Sergey

**Comment by dj-wasabi** [comment]
Hi,

So you would like to propose the following change:
Add:
```
manage_docroot => false
```

This is only for allowing it via an ip instead of an fqdn? Am I correct?

**Comment by ju5t** [comment]
You can do this already without changing any of the code. In your Apache class definition:

```
class { 'apache':
  mpm_module => 'prefork',
  default_vhost => false,
  default_ssl_vhost => false,
}
```

**Comment by dj-wasabi** [comment]
This is indeed easier to do, thank you @ju5t . If this work @szemlyanoy  would you please let me know? I can update the documentation about this.

**Comment by szemlyanoy** [comment]
If I set 

class profile::zabbix::server {
  include ::zabbix::server
  include ::zabbix::web
  include ::zabbix::javagateway
  include ::mysql::client
  include ::apache::mod::php
  class { 'apache':
    mpm_module => 'prefork',
    default_vhost => false,
    default_ssl_vhost => false,
         }
}


then I get obvious duplicate resource error of Class[Apache]. I don't want to set manage_vhost=>false and replicate all params of apache in node definition(or profile)

**Comment by szemlyanoy** [comment]
To more seamless I propose to add new param  
$manage_docroot  with default to 'false' and let people override it if needed (like in my case)

Can I proceed with PR?

**Comment by ju5t** [comment]
You're setting defaults that may be causing issues on existing installations. We don't want Zabbix to be the default for example. You're also missing some documentation on your change.

**Comment by szemlyanoy** [comment]
ok for me it's absolutely fine to pass default 'false'.
Sorry what you mean by documentation?

**Comment by dj-wasabi** [comment]
I'll close this issue as the PR is accepted.
