### ISSUE TITLE
Issues with RHEL7 repos configuration

### ISSUE THREAD

**Issue by kuduka** [dj-wasabi/puppet-zabbix#183]
Hello,

On my RHEL7 releasever is set to 7Server:

```
# python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: langpacks, rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
Repository 'local' is missing name in configuration, using id
{'arch': 'ia32e',
 'basearch': 'x86_64',
 'releasever': '7Server',
 'uuid': '20a2ac23-07d1-4d8a-9ae9-7fd280a712e6'}
```

And Zabbix repo is configured as:
```
# grep base /etc/yum.repos.d/Zabbix_7_x86_64.repo
baseurl=http://repo.zabbix.com/zabbix/2.4/rhel/$releasever/$basearch/

```

But that URL doesn't exist, just http://repo.zabbix.com/zabbix/2.4/rhel/7/ and yum is looking for http://repo.zabbix.com/zabbix/2.4/rhel/7Server/

Workaround that worked for me, but no idea if it will break something else:

```
diff --git a/manifests/repo.pp b/manifests/repo.pp
index 4ae59f0..1f69f8d 100644
--- a/manifests/repo.pp
+++ b/manifests/repo.pp
@@ -40,7 +40,7 @@ class zabbix::repo (
         $reponame     = $majorrelease
       }
       default       : {
-        $majorrelease = '$releasever'
+        $majorrelease = $::operatingsystemmajrelease
         $reponame     = $::operatingsystemmajrelease
       }
     }
```

**Comment by amgrice** [comment]
That is exactly what I had to do to patch this issue with RHEL as well. Thanks for posting this, @kuduka

**Comment by dj-wasabi** [comment]
I believe I had fixed this a while ago. Which version of the puppet module you are using right now?

**Comment by kuduka** [comment]
I'm using your master version and 2.1.1 tag, same issue on both.

**Comment by amgrice** [comment]
I saw the issue on master and at 2.1.1 as well.

**Comment by dj-wasabi** [comment]
I just pushed an fix for this. Would you please validate it?

**Comment by ericsysmin** [comment]
At @dj-wasabi dj-wasabi, should we work on a validation check in the commit for this? or you think it's probably solved and wont happen again, im surprised it didn't get picked up on build test

**Comment by dj-wasabi** [comment]
@ericsysmin Me too.
This weekend I try to release 2.2.0, so this fix will be in it.

**Comment by kuduka** [comment]
Fix worked for me with 2.2.0 tag, thank you!

# grep baseurl /etc/yum.repos.d/Zabbix_7_x86_64.repo
baseurl=http://repo.zabbix.com/zabbix/2.4/rhel/7/$basearch/

**Comment by ericsysmin** [comment]
sweet! @dj-wasabi  lets close this :+1:

**Comment by amgrice** [comment]
Was able to install the 2.2.0 module today, worked as expected. Sorry for the delay in reporting back!

**Comment by dj-wasabi** [comment]
Nice! Will close this ticket!
