### ISSUE TITLE
Zabbix 3.0 Proxy Postgres DB Schema Using Incorrect File

### ISSUE THREAD

**Issue by channone-arif-nbcuni** [dj-wasabi/puppet-zabbix#186]
Zabbix proxy server 3.0 loading create.sql.gz instead of schema.sql.gz

[zabbix-module-fix.txt](https://github.com/dj-wasabi/puppet-zabbix/files/159596/zabbix-module-fix.txt)

**Comment by dj-wasabi** [comment]
Hi @channone-arif-nbcuni 

Thank you. Have fixed this. Try to release this weekend to the forge.

**Comment by dj-wasabi** [comment]
I just pushed an release (v2.2.0) to the forge.
