### ISSUE TITLE
AMZ Linux Support 

### ISSUE THREAD

**Issue by channone-arif-nbcuni** [dj-wasabi/puppet-zabbix#187]
This should allow managing of repos for AWS Amazon Linux. 

Can also be combined with the case definition above it.   'PSBM' ,'Amazon'

[diff1.txt](https://github.com/dj-wasabi/puppet-zabbix/files/160827/diff1.txt)

**Comment by ericsysmin** [comment]
I will take a look and work on an addition @channone-arif-nbcuni

**Comment by ericsysmin** [comment]
Added support, if they do change to systemd i will definitely need to modify to do OS Version matching

**Comment by ericsysmin** [comment]
@dj-wasabi we can close this issue

**Comment by dj-wasabi** [comment]
I just accepted the PR. Will close this. Thanks!
