### ISSUE TITLE
SELinux - CentOs 7

### ISSUE THREAD

**Issue by clintonm9** [dj-wasabi/puppet-zabbix#190]
The zabbix server kept saying "Zabbix is not running".

After digging into it, it was an SELinux issue. I had to add the following:

`selboolean { 'httpd_can_network_connect':
	  name       => 'httpd_can_network_connect',
		persistent => 'true',
	  value      => 'on',
}`

Could you look at making that an option or do it by default?

**Comment by bastelfreak** [comment]
@clintonm9 please have a look at https://github.com/dj-wasabi/puppet-zabbix/pull/191

**Comment by dj-wasabi** [comment]
I'll close this issue, as @bastelfreak provided an improvement for this.
