### ISSUE TITLE
Update zabbixapi gem to 2.4.7 form Zabbix 3.0

### ISSUE THREAD

**Issue by tverhoeven** [dj-wasabi/puppet-zabbix#196]
It seems one thing was missed when adding Zabbix 3.0 support. The zabbixapi gem used to make the exported resources work is still by default set to install version 2.4.4. But only version 2.4.7 (or later) of the gem supports the Zabbix 3.0 API.

This section of the web.pp should be correct:
    # Determine correct zabbixapi version.
    case $zabbix_version {
      '2.2' : {
        $zabbixapi_version = '2.2.2'
      }
      '2.4' : {
        $zabbixapi_version = '2.4.4'
      }
      default : {
        $zabbixapi_version = '2.4.7'
      }
    }

Thanks, Tim

**Comment by dj-wasabi** [comment]
Hi @tverhoeven 

I just pushed the fix for this. Thanks for letting me know.
