### ISSUE TITLE
Unable to create host with zabbixapi - Invalid params

### ISSUE THREAD

**Issue by chihoko** [dj-wasabi/puppet-zabbix#37]
I'm having a problem with exported resources. I've configured the following class on a server

    class { '::zabbix::agent':
        agent_use_ip       => false,
       zabbix_version     => '2.4',
       server             => 'host.test.com',
       manage_resources   => true,
       manage_repo        => true,
       manage_firewall    => true,
       zbx_group          => 'Linux servers',
       zbx_templates      => ['C_Linux_base'],
       logfilesize        => '10',
       monitored_by_proxy => '',
    }

But when running puppet on the zabbix server I get the following error:

```ruby
Wrapped exception:
Server answer API error:
 {
  "data": "Incorrect arguments passed to function.",
  "code": -32602,
  "message": "Invalid params."
}
 on request:
 {
  "params": [
    {
      "available": 1,
      "interfaces": [
        {
          "dns": "host.test.com",
          "main": 1,
          "type": 1,
          "useip": 0,
          "port": "10050",
          "ip": null
        }
      ],
      "status": 0,
      "proxy_hostid": null,
      "host": "host.test.com",
      "templates": [
        10056
      ],
      "groups": [
        {
          "groupid": 6
        }
      ]
    }
  ],
  "jsonrpc": "2.0",
  "method": "host.create",
  "auth": "341c3fbe85ke0ed60a1c15a560ab27ec",
  "id": 10965
}
````

Looking at the [Zabbix API docs](https://www.zabbix.com/documentation/2.2/manual/api/reference/host/create) it does look like the template array should be in the format `"templateid": "20045"`, is this the problem?

Any help would be much appreciated.

**Comment by dj-wasabi** [comment]
Will take a look at it. But my test environment (Puppetmaster + puppetdb) has some problems which needs to be solved first before I can take a look at this issue. So it takes some time, probably a few days (I've some other projects which also needs time though .. :-)). 

Could please tell me in the meantime the following:
- Which version of the module you are using? 
- Which OS you are using? 

Thanks.
Kind regards,
Werner

**Comment by chihoko** [comment]
Hi Werner,

Thanks, we are using version 1.0.0 on Centos 6.6.

**Comment by genebean** [comment]
I found this too and submitted a PR: dj-wasabi/puppet-zabbix#40
