### ISSUE TITLE
Zabbix proxy and hiera

### ISSUE THREAD

**Issue by Oyabi** [dj-wasabi/puppet-zabbix#42]
Hi,
I have now problem with zabbix-proxy and use of hiera.
Indeed, i receive this error `Error: Failed to apply catalog: Validation of Exec[ --port='' --owner='' --template=template0  'zabbix-proxy'] failed: ' --port='' --owner='' --template=template0  'zabbix-proxy'' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppet/modules/postgresql/manifests/server/database.pp:63
Wrapped exception:
' --port='' --owner='' --template=template0  'zabbix-proxy'' is not qualified and no path was specified. Please qualify the command or specify a path.`

I use this configuration :

    zabbix::proxy::zabbix_server_host: 'xxx.com'
    zabbix::proxy::database_type: 'mysql'
    zabbix::proxy::zabbix_server_port: '10051'

I have also tried to add this configuration : 

    zabbix::database::database_type: 'mysql'
    zabbix::database::zabbiix_type: 'proxy'
    zabbix::database::database_name: 'zabbix-proxy'
    zabbix::database::database_user: 'zabbix-proxy'
    zabbix::database::database_password: 'test'

But I have got this error `Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Class[Zabbix::Database] is already declared; cannot redeclare at /etc/puppet/modules/zabbix/manifests/proxy.pp:408 on node teliboxexpress.local.tec6.net
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

Have you an idea to what I doing wrong ?

Thank you and have a nice day ;)

**Comment by dj-wasabi** [comment]
Hi Oyabi,

I noticed this:
```
zabbix::database::zabbiix_type: 'proxy'
```
It has 2 i in zabbiix_type, but thats not the problem. :-)

Is this an 1 node setup? So the zabbix proxy and the mysql database is running on the same server? 
If this is the case, I would use this:
```
zabbix::proxy::zabbix_server_host: 'xxx.com'
zabbix::proxy::database_type: 'mysql'
zabbix::proxy::zabbix_server_port: '10051'
zabbix::proxy::database_name: 'zabbix-proxy'
zabbix::proxy::database_user: 'zabbix-proxy'
zabbix::proxy::database_password: 'test'
```

The `zabbix::proxy` class already does an include of the `zabbix::database::<database_type>` class, so you won't have to define it again.

Thank you, you also have a nice day! :-)

Kind regards,
Werner

**Comment by Oyabi** [comment]
Hi Werner, ;)
I have still this error `Error: Failed to apply catalog: Validation of Exec[ --port='' --owner='' --template=template0  'zabbix-proxy'] failed: ' --port='' --owner='' --template=template0  'zabbix-proxy'' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppet/modules/postgresql/manifests/server/database.pp:63
Wrapped exception:
' --port='' --owner='' --template=template0  'zabbix-proxy'' is not qualified and no path was specified. Please qualify the command or specify a path.`.
I have copy/past your line of code.
I made an includes like this :

    ---
    classes:
      - zabbix::proxy
      # - mysql::server # doesn't work even if I uncomment.

Another question, it's possible to format these line (and zabbix-agent) like zabbix::userparameter ? 

    zabbix::userparameter::data:
      RAID:
        content: softRaid.status[*], cat /proc/mdstat | grep $1 -B0 -C1 | tail -n 1 | cut -d...

Thank you for your help

**Comment by dj-wasabi** [comment]
Hi Oyabi,

To be honest, I don't know why it gives an error on the postgres. You have specified mysql with this:
```
zabbix::proxy::database_type: 'mysql'
```
So, it will be using the mysql as backend.

You don't have something like this in your hiera tree?
```
classes:
  - postgresql::server
```

An different setup which may help, what if you use it like this:
```
classes:
  - zabbix::proxy
  - mysql::server

zabbix::params::database_type: 'mysql'
zabbix::params::proxy_database_name: 'zabbix-proxy'
zabbix::params::proxy_database_user: 'zabbix-proxy'
zabbix::params::proxy_database_password: 'test'
zabbix::proxy::zabbix_server_host: 'xxx.com'
zabbix::proxy::zabbix_server_port: '10051'
```
We set the params which are included in the zabbix::proxy classes..

The zabbix::userparameter::data should work like you have mentioned.

Kind regards,
Werner

**Comment by Oyabi** [comment]
Hi Werner, 
it doesn't work either. 
I have only put the code you give it to me. (first then second)
It happen to work well with PostgreSQL (no error) thus I think it's a bug with MySQL.

**Comment by dj-wasabi** [comment]
I just pushed the fix for your MySQL issue. Would you please test if the error is gone?

**Comment by Oyabi** [comment]
I have test this fix yesterday but I have always this error and I don't know why.
I try to escaped the quotes and I got same result.
I probably can put zabbixproxy as user but it's be better if we can let's default parameter.

**Comment by dj-wasabi** [comment]
Hi Oyabi,

With the latest change I added some quotes, from:
```
mysql -h ${database_host} -u ${database_user} -p${database_password} -D ${database_name}
```
to
```
mysql -h '${database_host}' -u '${database_user}' -p'${database_password}' -D '${database_name}'
```
So if I read it correctly, this didn't solve your problem.

I'll close this ticket, because the original question is solved and the bug is from puppetlabs-mysql module.

Kind regards,
Werner
