### ISSUE TITLE
manage_repo false still installs repo

### ISSUE THREAD

**Issue by peterjam28** [dj-wasabi/puppet-zabbix#43]
Using wdijkerman-zabbix-1.0.0, when manage_repo in zabbix::server is false, zabbix::repo is still required (and installs the repos).
This is because of the following: -

  # Installing the packages
  package { "zabbix-server-${db}":
    ensure  => $zabbix_package_state,
    require => Class['zabbix::repo'],
  }

**Comment by peterjam28** [comment]
This is fixed in the latest code, but not released.

**Comment by dj-wasabi** [comment]
Hi peterjam28,

Yes, I try to release the 1.0.2 this week to the forge. You can download the latest from github if needed.

Kind regards,
Werner

**Comment by peterjam28** [comment]
Thanks werner,

I downloaded the latest already,  but will look forward to the release.
Excellent module, thanks.
