### ISSUE TITLE
allow setting location of psql

### ISSUE THREAD

**Issue by peterjam28** [dj-wasabi/puppet-zabbix#44]
The path for psql in zabbix::database::postgresql is: -
/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

I have it installed in /opt/postgres/9.3/bin.
Can we have a parameter to set the path for non-standard.

I can create a symlink, but it seems a shame that it's necessary.

**Comment by dj-wasabi** [comment]
Hi Peterjam28

I just pushed an solution for this. The following classes are changed so they have an extra parameter `database_path`:
* zabbix::server
* zabbix::proxy
* zabbix::database::postgresql
* zabbix::database::mysql

You can use it like this:
```
class { 'zabbix':
  zabbix_url    => 'zabbix.example.com',
  database_path => '/opt/postgres/9.3/bin',
}
```
The value will be appended to the original "PATH" (`/bin:/usr/bin:/usr/local/sbin:/usr/local/bin`), so you don't have to worry about other path settings like '/bin' or '/sbin' for breaking the configuration. 

In your setup, "PATH" will be like this when executing the psql commands: 
```
/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/opt/postgres/9.3/bin
```

Is this acceptable for you?

Kind regards,
Werner

**Comment by peterjam28** [comment]
That is exactly what I was hoping for,  thanks.   Will this be in 1.0.2?

**Comment by dj-wasabi** [comment]
No, in 1.1.0. 
When I got confirmation from an other issue (Hopefully today or tomorrow), I'll create an git tag and create the release for the forge.

**Comment by dj-wasabi** [comment]
I uploaded release 1.1.0 to the forge.
I'll close this ticket. If you have any questions or problems at all, please reopen this ticket or create a new ticket please.

Kind regards,
Werner
