### ISSUE TITLE
Zabbix-proxy

### ISSUE THREAD

**Issue by Oyabi** [dj-wasabi/puppet-zabbix#45]
Hi again,
Is it possible to change the hostname in the zabbix-proxy configuration file?
I don't found how to do that.
Something like that `zabbix::proxy::hostname: 'My_Custom_Name'`

Regards.

**Comment by dj-wasabi** [comment]
Hi Oyabi,

With the current release it is not possible to do this.
If the need for this is high, I think I can arrange something. Won't be before the weekend though.

Kind regards,
Werner

**Comment by Oyabi** [comment]
Hi Werner,
Indeed I need this functionnality but it's not really urgent don't worry.
Thank you again ;)

Regards,
Oyabi.

**Comment by dj-wasabi** [comment]
Hi Oyabi,
I just pushed an fix for this. You could use the new parameter `hostname`.

Kind regards,
Werner

**Comment by Oyabi** [comment]
Thank you ;)
