### ISSUE TITLE
listenip bug

### ISSUE THREAD

**Issue by JvdW** [dj-wasabi/puppet-zabbix#49]
Found a typo, probably relating to atleast agent.pp listenip.
The following code block has its comparison backwards:
  # Find if listenip is set. If not, we can set to specific ip or
  # to network name. If more than 1 interfaces are available, we
  # can find the ipaddress of this specific interface if listenip
  # is set to for example "eth1" or "bond0.73".
  if $listenip == undefined {
    if ($listenip =~ /^(eth|bond|lxc).*/) {
      $int_name = "ipaddress_${listenip}"
      $listen_ip = inline_template('<%= scope.lookupvar(int_name) %>')
    } elsif is_ip_address($listenip) {
      $listen_ip = $listenip
    } else {
      $listen_ip = $::ipaddress
    }
  } else {
    $listen_ip = $::ipaddress
  }
 
It should be:
  # Find if listenip is set. If not, we can set to specific ip or
  # to network name. If more than 1 interfaces are available, we
  # can find the ipaddress of this specific interface if listenip
  # is set to for example "eth1" or "bond0.73".
  if $listenip != undefined {
    if ($listenip =~ /^(eth|bond|lxc).*/) {
      $int_name = "ipaddress_${listenip}"
      $listen_ip = inline_template('<%= scope.lookupvar(int_name) %>')
    } elsif is_ip_address($listenip) {
      $listen_ip = $listenip
    } else {
      $listen_ip = $::ipaddress
    }
  } else {
    $listen_ip = $::ipaddress
  }

**Comment by dj-wasabi** [comment]
Hi JvdW,

Thank you for making time to create this issue. 
I'll take a look at it. This was recently changed with pull request #46 

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
Hi JvdW,

I'll close this ticket, because you provided the pull request.
Thanks again!

Kind regards,
Werner
