### ISSUE TITLE
Bad syntax in manifests/proxy.pp

### ISSUE THREAD

**Issue by fredprod** [dj-wasabi/puppet-zabbix#50]
In forge.puppetlabs repository
casesize instead of cachesize
check comments we have to use this param in MB not in B
for example, just pust 32 if you want 32M in CacheSize value

**Comment by dj-wasabi** [comment]
Hi Fredprod,

I accepted your pull request (Thanks again!) and updated the comment in manifests/proxy.pp (and configuration template) to use MB.

Kind regards,
Werner
