### ISSUE TITLE
Support for Centos 7

### ISSUE THREAD

**Issue by minorOffense** [dj-wasabi/puppet-zabbix#55]
Are you accepting merge requests or have plans to support centos 7?

**Comment by dj-wasabi** [comment]
Hi minorOffense,

Yes, I'll do merge requests, so if it is an bug or a new functionality like CentOS 7, I'll do accept almost anything. :-)

I don't have anything yet on CentOS 7...

Kind regards,
Werner

**Comment by f0** [comment]
Hi,

i run the agent / proxy and server on el7 (with this module ), no problems

regards f0

**Comment by dj-wasabi** [comment]
Hi,

Thanks for your answer f0. I do have ran some test on el7 and everything works as expected. So with the next release I'll support el7 as well.

Thanks minorOffense for creating this issue.
Kind regards,
Werner

**Comment by minorOffense** [comment]
Ok great! We were using it on centos 7 but had installation issues with the zabbix client (couldn't find the package or something). Maybe zabbix fixed the upstream names in the repos since we last tried.

Thanks for the great module!

**Comment by dj-wasabi** [comment]
Your welcome!
Enjoy it! :-)
