### ISSUE TITLE
You can not configure hostname in zabbix::proxy

### ISSUE THREAD

**Issue by xdexter** [dj-wasabi/puppet-zabbix#59]
When I declare the proxy hostname by class, for example:

class { 'zabbix::proxy':
    zabbix_package_state  => 'latest',
    hostname              => 'proxy.domain.com',
    database_host         => 'localhost',
    database_type         => 'mysql',
    manage_database       => false,
    database_name         => 'zabbix_proxy',
    database_user         => 'zabbix',
    database_password     => 'zabbix',
    zabbix_server_host    => 'server.domain.com',
    database_socket       => '/var/lib/mysql/mysql.sock',
    database_port         => '3306',
    offlinebuffer         => '8',
    logfile               => '/var/log/zabbix/zabbix_proxy.log',
    logfilesize           => '0',
    zabbix_server_port    => '10051',
    pidfile               => '/var/run/zabbix/zabbix_proxy.pid',
  }

the hostname is not set in zabbix_proxy.conf file, but the server FQDN.

That would work correct?

I'm using:
Centos 6.6
Zabbix Agent 2.4
Zabbix Proxy 2.4
Puppet 3.7.4

Thank you

**Comment by dj-wasabi** [comment]
Hi xdexter,

Thanks for making time to create this issue. 
I found the problem, will push later this day.

Kind regards,
Werner

**Comment by xdexter** [comment]
Hello Werner,

Perfect, I'm waiting.

Kind Regards

**Comment by dj-wasabi** [comment]
Hi xdexter,

I just pushed it. Please let me know if you have any troubles.

Kind regards,
Werner

**Comment by xdexter** [comment]
Hello, 

Perfect, is now working!

thank you very much

**Comment by Oyabi** [comment]
Hi, 
I think I have the same problem but with hiera.
Here my code : 
zabbix::proxy::zabbix_server_host: 'my.domain'
zabbix::proxy::database_type: 'mysql'
zabbix::proxy::zabbix_server_port: '10051'
zabbix::proxy::database_name: 'zabbixproxy'
zabbix::proxy::database_user: 'zabbixproxy'
zabbix::proxy::database_password: 'password'
zabbix::proxy::hostname: 'P_domain'

Thank you.
