### ISSUE TITLE
Apt-key error in Ubuntu 14.04

### ISSUE THREAD

**Issue by HielkeJ** [dj-wasabi/puppet-zabbix#61]
In Ubuntu 14.04 we get this error every Puppet run:

Warning: /Apt_key[Add key: 79EA5ED4 from Apt::Source zabbix]: The id should be a full fingerprint (40 characters), see README.

The fingerprint should be:
Key fingerprint = FBAB D5FB 2025 5ECA B22E  E194 D13D 58E4 79EA 5ED4

**Comment by dj-wasabi** [comment]
Hi HielkeJ,

Thank you for making time to create this issue!
Will take a look at it.

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
Hi,

The user @exptom just created an Pull request for this issue and I just accepted this request.
So issue should be solved now.

Kind regards,
Werner
