### ISSUE TITLE
" Using allow is not supported in your Apache version"

### ISSUE THREAD

**Issue by stl-thorbach** [dj-wasabi/puppet-zabbix#72]
When deploying "zabbix::web" on a stand alone server or on a monolithic server I get the following error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template apache/vhost/_directories.erb:
  Filepath: /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/parser/functions/fail.rb
  Line: 3
  Detail: Apache::Vhost: Using allow is not supported in your Apache version
 at /etc/puppetlabs/puppet/environments/production/modules/apache/manifests/vhost.pp:545 on node zabbix-web.streetlightdata.net
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

All other modules (including "zabbix::database" and "zabbix::server) deploy without issues.

Setup is as follows (all instances running in google cloud):

Newly build puppet enterprise server [3.7.3 (Puppet Enterprise 3.7.1)]

Newly build zabbix server. Installed zabbix module with "puppet module install wdijkerman-zabbix"

Class: apache
mpm_module = "prefork"

Class: apache::mod::php

Class: zabbix::web
zabbix_url = "zabbix-web.test.net"

**Comment by dj-wasabi** [comment]
Hi stl-thorbach,

Thank you for making time to create this issue. What kind of OS are you running? What version of Apache? 2.2 or 2.4?

Kind regards,
Werner

**Comment by stl-thorbach** [comment]
Thank you for getting back to me Werner.

My apologies for omitting some of the fundamental information.

I am running Ubuntu 14.04:
Linux 3.16.0-33-generic #44~14.04.1-Ubuntu SMP Fri Mar 13 10:33:29 UTC 2015
x86_64 x86_64 x86_64 GNU/Linux

and apache 2.4:
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Mar 10 2015 13:05:59
Server's Module Magic Number: 20120211:27
Server loaded:  APR 1.5.1-dev, APR-UTIL 1.5.3
Compiled using: APR 1.5.1-dev, APR-UTIL 1.5.3
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"

That is the default apache version that puppet installs.

Please let me know if you need any additional information.

Kind Regards

THOR


Thorsten Bach
StreetLight Data Inc.
Director of IT and Operations
thor.bach@streetlightdata.com
415-881-7539

**Comment by dj-wasabi** [comment]
Hi Thorsten,

Thanks for your comment.

One question, before I start investigating: How did you install this puppet module? Is this via the forge.puppetlabs.com or via github. I'm asking because around 5 days ago I accepted an pull request "bugfix for vhosts in apache 2.4 #67". This pr made it possible to also use Apache 2.4 with this module. 

If you installed it via the forge (1.2.0), then I would like to ask you if you can try to use the github version (Almost at 1.3.0). If you already are were using the latest github version, I'll try to investigate it.

Kind regards,
Werner

**Comment by stl-thorbach** [comment]
Thank you Werner.

I did use the "forge" version. I'll try the github version instead. I might
not get to this till late next week but I'll let you know the outcome as
soon as I know.

Best Regards

THOR


Thorsten Bach
StreetLight Data Inc.
Director of IT and Operations
thor.bach@streetlightdata.com
415-881-7539

**Comment by dj-wasabi** [comment]
Hi Thorsten,

No worries, take your time.
I'll release 1.3.0 somewhere in the next few days, so If you still have an problem I'll fix it in 1.3.1.

Kind regards,
Werner

**Comment by abien** [comment]
I ran into the same issue on CentOS-7 with apache 2.4
Switching from the forge to the git master made the error message disappear.

**Comment by TJM** [comment]
I am having this error on 1.4.1
