### ISSUE TITLE
Add dependency on apt

### ISSUE THREAD

**Issue by grundic** [dj-wasabi/puppet-zabbix#74]
Today I've tried to update from 0.5.1 to 1.3.0 and got an error:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: validate_re(): "FBABD5FB20255ECAB22EE194D13D58E479EA5ED4" does not match ["\\A(0x)?[0-9a-fA-F]{8}\\Z", "\\A(0x)?[0-9a-fA-F]{16}\\Z"] at /etc/puppet/environments/zabbix_update/modules/apt/manifests/key.pp:60 on node vagrant-ubuntu-precise-64
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Found, that you've updated keys in 32adbb8a27c8307684e37582a5271559a44ba646, but my apt module was of version 1.6.0. 
Could you, please, add dependency on apt module, so it would be easier to update later?
Thank you!

**Comment by dj-wasabi** [comment]
Hi Grundic,

Thank you for making time to create this issue.
Strange, I thought that I already did use "apt" as an dependency. I just pushed the dependency in metadata.json to github. Tomorrow I'll create 1.3.1 and upload it to the forge.

Kind regards,
Werner

**Comment by grundic** [comment]
Great, appreciate it!
