### ISSUE TITLE
Parametrise script folder

### ISSUE THREAD

**Issue by grundic** [dj-wasabi/puppet-zabbix#75]
It would be nice to give users possibility to select where they would like scripts to be installed.
Could you, please, parametrise script folder like `${include_dir}` for user parameters?
Thank you.

**Comment by dj-wasabi** [comment]
Hi Grundic,

Thanks you for making time to create this issue.
What do you mean with parametrise?

You can use with the current module:
```
class { 'zabbix::agent':
  server      => 192.168.1.1,
  include_dir => '/usr/local/scripts',
}
````

Kind regards,
Werner

**Comment by grundic** [comment]
Hello, Werner!
Sorry for unclear issue report.
What I meant is configuration of LLD script:
```
zabbix::userparameters { 'lld_snort.sh':
  script => 'puppet:///modules/zabbix/lld_snort.sh',
}
```
Correct me if I'm wrong, but according [userparameters.pp](https://github.com/dj-wasabi/puppet-zabbix/blob/master/manifests/userparameters.pp), `lld_snort.sh` script will always be placed to `/usr/bin`. And for example, I would like it to be placed under `/usr/local/bin`.
Thank you.

**Comment by dj-wasabi** [comment]
Hi,

I've pushed an fix for this almost an week ago to github.
You can use it like this now:

```
zabbix::userparameters { 'lld_snort.sh':
  script     => 'puppet:///modules/zabbix/lld_snort.sh',
  script_dir => '/usr/local/bin'
}
```

Default, '/usr/bin' is used.

Will close this ticket to.

Kind regards,
Werner

**Comment by grundic** [comment]
Thank you very much, will test it soon.
