### ISSUE TITLE
Unable to install version 2.2

### ISSUE THREAD

**Issue by mesouug** [dj-wasabi/puppet-zabbix#76]
Good day.

After updating from 1.0.0 version to 1.3.0 I'm no longer able to install zabbix agent version 2.2.
I've researched and found following commit that changed installation behaviour.

https://github.com/dj-wasabi/puppet-zabbix/commit/e5429920e0532485c4518f73205329dbf649b77e

I'm using Foreman with this module. Can you please assist how to force v2.2?

Thanks,
Mikhail.

**Comment by dj-wasabi** [comment]
HI mesouug,

Thank you for making time to create this issue.
Could you please tell me which Operating System you are using? Do you use Puppet Community or Enterprise?

Kind regards,
Werner

**Comment by mesouug** [comment]
Good day.

As ENC I'm using http://theforeman.org/ on CentOS 6. Target VM is Ubuntu 12.04. Puppet Community.

Thanks,
Mikhail.

**Comment by IceBear2k** [comment]
Yes, behavior for Foreman changed with this as well. You'll have to additionally add "zabbix::repo" to your host and define "zabbix_version" as "2.2". That should work.

**Comment by mesouug** [comment]
Good day.

Works like charm!

Thanks,
Mikhail.
