### ISSUE TITLE
manage_firewall is set to 'false' by default

### ISSUE THREAD

**Issue by mimra** [dj-wasabi/puppet-zabbix#86]
As per documentation it says "manage_firewall: Wheter you want to manage the firewall. If true (Which is default), iptables will be configured to allow communications to zabbix ports."

However 'manage_firewall' is set to 'false' in params.pp file. I had to manually set it to 'true' to get it working. Either documentation should be updated or params.pp should be modified so that manage_firewall is default to 'true.
Thanks

**Comment by f0** [comment]
does it fail if iptables is not active? in this case it should be false,
otherwise its safe to set to true

2015-05-07 21:05 GMT+02:00 mimra <notifications@github.com>:

**Comment by dj-wasabi** [comment]
Hi,

The documentation is updated just a few minutes ago. It should not be enabled at default. It's an user decision for enabling the iptables config, not "my" decision. :-)

Kind regards,
Werner
