### ISSUE TITLE
Need to overide php_values

### ISSUE THREAD

**Issue by szemlyanoy** [dj-wasabi/puppet-zabbix#89]
Hi,

I want to increase memory_limit for zabbix vhost. I suppose that below default should be overwritten in zabbix::web where apache::vhost type is defined

 custom_fragment => "
   php_value max_execution_time 300
   php_value memory_limit 128M
   php_value post_max_size 16M
   php_value upload_max_filesize 2M
   php_value max_input_time 300
   php_value always_populate_raw_post_data -1
   # Set correct timezone
   php_value date.timezone ${zabbix_timezone}",

But I seems stuck, since I need to do it  via hiera.

I tried this but no luck

zabbix::web:
  zabbix_vhost:
    php_values:
      memory_limit: 256

How it can be changed? 

Thanks
Sergey

**Comment by dj-wasabi** [comment]
Hi Sergey,

Thank you for making time to create this issue.

I just checked, but these values are "hardcoded" into the Apache virtual host configuration. So for now the only way to change this is to update the manifests/web.pp file to your needs.

I can however, make it overridable with parameters, but that requires some time before you can enjoy it. I might have some time left this weekend to start with this, but can't guarantee it.

Kind regards,
Werner

**Comment by szemlyanoy** [comment]
Hi Werner,

Thanks for getting back to me.
I will proceed with web.pp class altering as you recommended. Will keep watching on your updates. 

Cheers
Sergey

**Comment by dj-wasabi** [comment]
Hi Sergey,

I just pushed the code to github for this.
Please let me know if you miss anything.

Kind regards,
Werner

**Comment by szemlyanoy** [comment]
Hi Werner,

Yes it works cool!

But I noticed this change also:
WAS:   
$agent_hostname                 = $::fqdn
BECAME:
$agent_hostname                 = undef

in zabbix::params.pp

Was it done with some purpose?

Thanks ahead
Sergey

**Comment by szemlyanoy** [comment]
Noticed this fix https://github.com/dj-wasabi/puppet-zabbix/issues/80  
Now is clear

**Comment by dj-wasabi** [comment]
Nice! Enjoy the fix. :-)
