### ISSUE TITLE
userparameter in hiera

### ISSUE THREAD

**Issue by pelacables** [dj-wasabi/puppet-zabbix#90]
Hello,

I've installed your puppet module in my environment. I'm using exported_resources and my nodes are automatically added to zabbix thanks to your module.
I'm following the instructions in https://github.com/dj-wasabi/puppet-zabbix#usage-zabbix-userparameters and configured some userparemeters in hiera:

    zabbix::userparameter::data:
        DiskIO_userparameters:
        source: 'puppet:///modules/zabbix/diskio.conf'
        template: 'DiskIO'

But the userparameter is not copied to the client.

I've hardcoded manage_reosurces=true in the module.

If I call it as zabbix:userparameters:

    zabbix::userparameters { 'diskIO' :
        source   => 'puppet:///modules/zabbix/diskio.conf',
        template => 'DiskIO',
    }

It works as expected.

So, at this point I'm not sure if I faced a bug in the zabbix/hiera usage or in the doc or something wrong in my code.

Am I doing something wrong? Do you have any working example? 

Many thanks for your great work in this module.

Cheers,
A

**Comment by dj-wasabi** [comment]
Hi pelacables,

Thank you for making time to create this issue.
Thats an good question that I can't answer right now. Will take a look at it.

I'll let you know when I found it. 

Kind regards,
Werner

**Comment by lamawithonel** [comment]
YAML is indentation-sensitive.  Try this:

```yaml
zabbix::userparameter::data:
    DiskIO_userparameters:
        source: 'puppet:///modules/zabbix/diskio.conf'
        template: 'DiskIO'
```

**Comment by dj-wasabi** [comment]
Solution provided by @lamawithonel, so I'll close this issue.
