### ISSUE TITLE
new postgresql instance

### ISSUE THREAD

**Issue by PHaroZ** [dj-wasabi/puppet-zabbix#91]
puppetlabs/postgresql v4.3.0
wdijkerman/zabbix v1.4.0

Creation of a new postgresql instance fail with following message : 

```
Notice: /Stage[main]/Zabbix::Database/Postgresql::Server::Db[zabbix_server]/Postgresql::Server::Database[zabbix_server]/Exec[/usr/lib/postgresql/9.1/bin/createdb --port='5432' --owner='' --template=template0  'zabbix_server']/returns:                                               ^
Error: /Stage[main]/Zabbix::Database/Postgresql::Server::Db[zabbix_server]/Postgresql::Server::Database[zabbix_server]/Exec[/usr/lib/postgresql/9.1/bin/createdb --port='5432' --owner='' --template=template0  'zabbix_server']: Failed to call refresh: /usr/lib/postgresql/9.1/bin/createdb --port='5432' --owner='' --template=template0  'zabbix_server' returned 1 instead of one of [0]
Error: /Stage[main]/Zabbix::Database/Postgresql::Server::Db[zabbix_server]/Postgresql::Server::Database[zabbix_server]/Exec[/usr/lib/postgresql/9.1/bin/createdb --port='5432' --owner='' --template=template0  'zabbix_server']: /usr/lib/postgresql/9.1/bin/createdb --port='5432' --owner='' --template=template0  'zabbix_server' returned 1 instead of one of [0]
```
This is due to <i>--owner=''</i>.

To avoid this I edit manifests/database.pp:130 to change
```puppet
        postgresql::server::db { $database_name:
          user     => $database_user,
          password => postgresql_password($database_user, $database_password),
          require  => Class['postgresql::server'],
        }
```
to
```puppet
        postgresql::server::db { $database_name:
          user     => $database_user,
          owner    => $database_user,
          password => postgresql_password($database_user, $database_password),
          require  => Class['postgresql::server'],
        }
```

And thanks for your job ;)

**Comment by dj-wasabi** [comment]
Hi PHaroZ,

Thank you for making time to create and investigate this issue. I'll take a look at it and let you know when this is fixed.

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
Hi,

I pushed an fix for this. Please let me know if you have any issues.

Kind regards,
Werner

**Comment by PHaroZ** [comment]
please could you say me how I can test your fix while it's not released in https://forge.puppetlabs.com (I've installed modules with puppet module install).
thx

**Comment by dj-wasabi** [comment]
Hi @PHaroZ 

You can clone this git repository on the puppet master. Or you have to wait till I release it on the forge. Don't know when I release it, but I only added the "owner    => $database_user," line. 

Kind regards,
Werner

**Comment by dj-wasabi** [comment]
Hi @PHaroZ 

I just uploaded the new release (1.5.0) to the forge.

Kind regards,
Werner

**Comment by PHaroZ** [comment]
thank you, i'll test that !
