### ISSUE TITLE
zabbix::repo doest not inherit zabbix::params

### ISSUE THREAD

**Issue by PHaroZ** [dj-wasabi/puppet-zabbix#93]
If zabbix::repo is used outside of zabbix::server, zabbix::params is not inherited, in such case default param values are not well resolved :
```
class zabbix::repo(
  $manage_repo    = $zabbix::params::manage_repo,
  $zabbix_version = $zabbix::params::zabbix_version,
) {
```
$manage_repo & $zabbix_version are undefined.

This need occurs when apt configuration is done in a different stage than other job. My case (stage <i>first</i> is done before <i>main</i>)
```puppet
  class {'::zabbix::repo':
    stage           =>  'first',
    manage_repo     =>  true,
    zabbix_version  =>  '2.4',
  }
  ...
  class {'::zabbix':
    zabbix_url      => 'zabbix.domain.tld',
    manage_firewall => true,
    manage_repo     => false,
    database_type   => 'postgresql',
  }
```
when i don't specify <i>manage_repo</i> & <i>zabbix_version</i>, <i>::zabbix::repo</i> does nothing.

So, is it possible that zabbix::repo inherits zabbix::params to enable default values ?

**Comment by dj-wasabi** [comment]
Hi @PHaroZ 

I pushed an fix for this several days ago. Would you please verify this and close the ticket?
Or please leave an comment with issues, ideas etc. :-)

Thanks!

Kind regards,
Werner
