### ISSUE TITLE
File extensions of Userparameters scripts

### ISSUE THREAD

**Issue by szemlyanoy** [dj-wasabi/puppet-zabbix#97]
Hi Werner,

I started moving userparameters into hiera. Maybe would be nice to control extensions of script files after they being landing to target server:
      file { "${script_dir}/${name}"

Now all scripts end up without any extensions. But it might be tricky to realize though

Regards
Sergey

**Comment by szemlyanoy** [comment]
Also I have noticed that class zabbix::userparameter doesnt merge hiera hash from host and hostgroups yamls

**Comment by dj-wasabi** [comment]
Hi Sergey,

You are right! Will take a look at it.

Kind regards,
Werner

**Comment by szemlyanoy** [comment]
Please check this pull request https://github.com/dj-wasabi/puppet-zabbix/compare/master...szemlyanoy:patch-1#diff-4652d7fcfc557a6c4ba6540890d96bcd
